sudo: disable
language: cpp
dist: xenial

#
# Another option to install from custom APT repo
#
#before_install:
#  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
#  - sudo apt-get update -q
#  - sudo apt-get install -y libavutil-dev libavcodec-dev libavformat-dev
##  - sudo apt-get install -y --no-install-recommends --no-install-suggests graphicsmagick-libmagick-dev-compat libgraphicsmagick++1-dev libwebp-dev libmaxminddb-dev libmysqlclient-dev libssl-dev libcurl4-openssl-dev pkg-config

services:
  - mysql

#
# Change password from default empty to smth else
#
#before_install:
#  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
#  - sudo mysql_upgrade -u root -proot
#  - sudo service mysql restart

addons:
  apt:
    sources:
    - sourceline: ppa:jonathonf/ffmpeg-3
    packages:
    - libavutil-dev
    - libavcodec-dev
    - libavformat-dev
    - graphicsmagick-libmagick-dev-compat
    - libgraphicsmagick++-dev
    - libwebp-dev
    - libmaxminddb-dev
    - libmysqlclient-dev
    - libssl-dev
    - libcurl4-openssl-dev
    - libhpdf-dev
    - libarchive-dev
    - wkhtmltox
    - pkg-config

script:
    # --- libxl will be installed to /usr/local/share/...
    # --- don't fail unit tests, if folder can't be created
    # --- use libxl from source-tree
    - mkdir /usr/local/share/timecard.su || true
    - mkdir build && cd build && cmake .. && chmod a+x ./share/dev.timecard.su/ci-scripts/mysql_provisioning && ./share/dev.timecard.su/ci-scripts/mysql_provisioning && make -j4 && ctest --output-on-failure
