FROM ubuntu:xenial

LABEL maintainer="ivan.kuchin@gmail.com"
LABEL org.opencontainers.image.source="https://github.com/IvanKuchin/__BUILD_REPO__"
				     
# following two commands suppose to be reused from cache
RUN apt update &&  apt install --no-install-recommends --no-install-suggests -y git ca-certificates

RUN git clone --depth 1 https://github.com/IvanKuchin/__BUILD_REPO__.git /backend
WORKDIR /backend

RUN apt-get install --no-install-recommends --no-install-suggests -y software-properties-common
RUN add-apt-repository -y ppa:jonathonf/ffmpeg-4
RUN apt update
RUN apt-get install --no-install-recommends --no-install-suggests -y \ 
		build-essential \
		cmake \
	        ffmpeg \
	        graphicsmagick-libmagick-dev-compat \
	        libavcodec-dev \
	        libavformat-dev \
	        libavutil-dev \
	        libcurl4-openssl-dev \
	        libgraphicsmagick++-dev \
	        libhpdf-dev \
	        libmaxminddb-dev \
	        libmysqlclient-dev \
		libssl-dev \
	        libwebp-dev \
		pkg-config

RUN git rev-parse HEAD > ./supplemental/git/git_commit_id
RUN mkdir build
RUN cd build && cmake .. && make -j4 && make install

################################
## DB is a separate container ##
################################
# RUN echo mysql-server mysql-server/root_password password root | debconf-set-selections
# RUN echo mysql-server mysql-server/root_password_again password root | debconf-set-selections

# RUN apt-get install --no-install-recommends --no-install-suggests -y mysql-server

# COPY my_script.sh /root/
# COPY sql /root/
# COPY pre.sql /root/
# RUN  chmod +x /root/my_script.sh

############################################################
## forward request and error logs to docker log collector ##
############################################################
#RUN ln -sf /dev/stdout /var/log/nginx/access.log \
# && ln -sf /dev/stderr /var/log/nginx/error.log

STOPSIGNAL SIGTERM

# CMD ["/root/my_script.sh"]
