#!/bin/bash

dir_mask=dev.
curr_dir=`pwd`

function git_folders()
{
    cd $curr_dir

    for i in $(ls | grep $dir_mask);
    do
	echo
	echo
	echo
	echo
	echo ------- $i
        cd $curr_dir/$i && ./supplemental/git/git_commit.pl -m "$commit_message"
        ret_val=$?
        if [ $ret_val -gt 0 ]
        then
            echo [FAIL]
            exit $ret_val
        fi
    done
}

echo git commit message:
read commit_message

git_folders
